const List explore_json = [
  {
    "img": "assets/images/girls/img_1.jpeg",
    "name": "Rachel",
    "likes1": ["Water Sports", "Puppies"],
    "likes2": ["Italian", "Coding"],
  },
  {
    "img": "assets/images/girls/img_2.jpeg",
    "name": "Monica",
    "likes1": ["Water Sports", "Puppies"],
    "likes2": ["Italian", "Coding"],
  },
  {
    "img": "assets/images/boys/image1.jpg",
    "name": "Zlatan",
    "likes1": ["Water Sports", "Puppies"],
    "likes2": ["Italian", "Coding"],
  },
  {
    "img": "assets/images/girls/img_3.jpeg",
    "name": "Phoebe",
    "likes1": ["Water Sports", "Puppies"],
    "likes2": ["Italian", "Coding"],
  },
  {
    "img": "assets/images/boys/image2.jpg",
    "name": "Logan",
    "likes1": ["Water Sports", "Puppies"],
    "likes2": ["Italian", "Coding"],
  },
  {
    "img": "assets/images/girls/img_4.jpeg",
    "name": "Rachel",
    "likes1": ["Water Sports", "Puppies"],
    "likes2": ["Italian", "Coding"],
  },
  {
    "img": "assets/images/girls/img_5.jpeg",
    "name": "Monica",
    "likes1": ["Water Sports", "Puppies"],
    "likes2": ["Italian", "Coding"],
  },
  {
    "img": "assets/images/boys/image3.jpg",
    "name": "Joey",
    "likes1": ["Water Sports", "Puppies"],
    "likes2": ["Italian", "Coding"],
  },
  {
    "img": "assets/images/girls/img_6.jpeg",
    "name": "Phoebe",
    "likes1": ["Water Sports", "Puppies"],
    "likes2": ["Italian", "Coding"],
  },
  {
    "img": "assets/images/girls/img_7.jpeg",
    "name": "Rachel",
    "likes1": ["Water Sports", "Puppies"],
    "likes2": ["Italian", "Coding"],
  },
  {
    "img": "assets/images/girls/img_8.jpeg",
    "name": "Monica",
    "likes1": ["Water Sports", "Puppies"],
    "likes2": ["Italian", "Coding"],
  },
  {
    "img": "assets/images/girls/img_9.jpeg",
    "name": "Rachel",
    "likes1": ["Water Sports", "Puppies"],
    "likes2": ["Italian", "Coding"],
  },
  {
    "img": "assets/images/girls/img_10.jpeg",
    "name": "Rachel",
    "likes1": ["Water Sports", "Puppies"],
    "likes2": ["Italian", "Coding"],
  },
];
